name: "install dependencies"
description: "Installs pipeline dependencies"

runs:
  using: composite
  steps:
    - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

    - name: Install cargo-binstall
      shell: sh
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

    - name: Setup `wkg`
      shell: bash
      run: |
        set -ex
        cargo binstall wkg

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu
        components: clippy, rustfmt
