[package]
name = "tofuya"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/bin/tofuya/main.rs"
name = "tofuya"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
toml = "1.1.2"
async-trait = "0.1"
mockall = "0.14"
dirs = "6.0"
url = { version = "2.5.8", features = ["serde"]}
comfy-table = "7.2.2"
wasmtime = { version = "44.0.0", features = ["async"]}
wasmtime-wasi = "44.0.0"
wit-component = "0.248.0"
wit-parser = "0.248.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
