[package]
name = "tofuya"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/bin/tofuya/main.rs"
name = "tofuya"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
toml = "1.1.2"
async-trait = "0.1"
mockall = "0.14"
dirs = "6.0"
url = { version = "2.5.8", features = ["serde"]}
comfy-table = "7.2.2"
wasmtime = { version = "45.0.1", features = ["async"]}
wasmtime-wasi = "45.0.1"
wasmtime-wasi-http = "45.0.1"
wit-component = "0.252.0"
wit-parser = "0.251.0"
axum = "0.8.9"
reqwest = { version = "0.13.3", features = ["native-tls"]}
oci-client = "0.17.0"
docker_credential = "1.4.0"
include_dir = "0.7.4"
rusqlite = { version = "0.40.1", features = ["bundled"]}
rusqlite_migration = { version = "2.6.0", features = ["from-directory"] }
hex = "0.4.3"
sha2 = "0.11.0"

[dev-dependencies]
test-temp-dir = "0.7.0"
temp-env = { version = "0.3.6", features = ["async_closure"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
