on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build wit interface
        shell: bash
        run: |
          just build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version without 'v' prefix
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Publish WIT
        uses: ./.github/actions/wit
        with:
          file: 'tofuya-interface.wasm'
          oci-description: 'The WASM Interface Type for Tofuya Plugins'
          oci-reference-without-tag: 'ghcr.io/tmuntaner/tofuya/plugin-interface'
          version: ${{ steps.version.outputs.VERSION }}
